Description: YAML Configuration file for unit test of ConfigFilePath overrides
ProductNames:
  - teams
  - exo
  - defender
  - aad
  - sharepoint
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports

# No Creds with this version
