name: Get Planets

on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  set-pattern:
    name: Get Planets
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Call Planet Module
        run: |
          Import-Module -Name .\utils\workflow\Get-Planet
          $allPlanets = Get-Planet
          Write-Output $allPlanets
