name: Get Planets

on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  set-pattern:
    name: Get Planets
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Call Planet Module
        run: |
          Import-Module (Join-Path -Path 'repo/utils/workflow' -ChildPath 'Get-Planet.psm1') -Function Get-Planet -Force
          # List the planets
          $allPlanets = Get-Planet
          Write-Output $allPlanets
