# Purpose: Run the linter against the PowerShell code

name: Lint Check for PowerShell

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

jobs:
  powershell-lint-check:
    name: MegaLint PowerShell Check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Config File
        run: cp Testing/Linting/MegaLinter/.mega-linter-powershell.yml .mega-linter.yml
      - name: Setup PSScriptAnalyzer settings
        run: cp Testing/Linting/MegaLinter/.powershell-psscriptanalyzer.psd1 .powershell-psscriptanalyzer.psd1
      - name: Lint PowerShell
        uses: oxsecurity/megalinter/flavors/dotnet@latest
