name: Nightly Product Functional Tests

# Run this workflow at midnight 
# on every Mon to Fri (b/c GMT -5)
on:
  schedule:
  - cron: 0 4 * * 1-5
  workflow_dispatch: 
  push:
    branches:
    - '652-add-nightly-product-functional-testing'

jobs:
  hello-world-test:
    name: Hello World Test
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell 
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
      # Let's start simple: Verify file exists
    - name: Check for file
      run: |
        if (!(Test-Path Testing/Functional/Products/ProductsX.Tests.ps1 -PathType Leaf))
        {
          core.setFailed('Product test file not found.')
        }
