# Purpose:  Run the CI/CD pipeline that tests, packages, and publishes ScubaGear.
# Note:  This pipeline is a work in progress.  At the moment, it is only doing linting, syntax checking, and unit testing.

name: CI/CD Pipeline

on:
  push:
    branches:
      - 825-create-initial-software-dev-pipeline
  pull_request:
  workflow_dispatch:

jobs:
  test-files:
    name: Test for Changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check for Changes
        uses: dorny/paths-filter@v3
        id: file-changes
        with:
          filters: |
            yaml-files:
              - "**.yml"
              - "**.yaml"
            powershell-files:
              - "**.ps1"
              - "**.psm1"
              - "**.psd1"
              - "**.pssc"
              - "**.psrc"
              - "**.ps1xml"
              - "**.cdxml"
            markdown-files:
              - "**.md"
            rego-files:
              - "**.rego"
    outputs:
      yaml-changes: ${{ steps.file-changes.outputs.yaml-files }}
      powershell-changes: ${{ steps.file-changes.outputs.powershell-files }}
      markdown-changes: ${{ steps.file-changes.outputs.markdown-files }}
      rego-changes: ${{ steps.file-changes.outputs.rego-files }}
  lint-yaml:
    name: Lint
    needs:
      - test-files
    if: needs.test-files.outputs.yaml-changes == 'true'
    uses: cisagov/ScubaGear/.github/workflows/run_linter_yaml.yaml@825-create-initial-software-dev-pipeline
  lint-powershell:
    name: Lint
    needs:
      - test-files
    if: needs.test-files.outputs.powershell-changes == 'true'
    uses: cisagov/ScubaGear/.github/workflows/run_linter_powershell.yaml@825-create-initial-software-dev-pipeline
  syntax:
    name: Syntax
    needs:
      - test-files
    if: needs.test-files.outputs.markdown-changes == 'true'
    uses: cisagov/ScubaGear/.github/workflows/run_markdown_check.yaml@825-create-initial-software-dev-pipeline
  unit-powershell:
    name: Unit
    needs:
      - test-files
    if: needs.test-files.outputs.powershell-changes == 'true'
    uses: cisagov/ScubaGear/.github/workflows/run_powershell_tests.yaml@825-create-initial-software-dev-pipeline
  unit-opa:
    name: Unit
    needs:
      - test-files
    if: needs.test-files.outputs.rego-changes == 'true'
    uses: cisagov/ScubaGear/.github/workflows/run_opa_tests.yaml@825-create-initial-software-dev-pipeline
