on:
on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Release Name"
        required: true
        type: string
      version:
        description: "Release Version (e.g., 1.2.4)"
        required: true
        type: string
      useDevCredentials:
        description: "Use development instead of production credentials"
        required: false
        type: boolean
        default: true

name: Build and Sign Release

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: Development
    env:
      SCUBA_CODE_SIGNING_CREDS: ${{ secrets.SCUBA_CODE_SIGNING_CREDS }}
      RELEASE_VERSION: ${{ inputs.version }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true          
      - name: Sign Module
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $DebugPreference='Continue'
            dotnet --version
            dotnet tool install --global AzureSignTool --version 4.0.1
            #TODO: Add Key Vault info to environment secret
            . repo/utils/DeployUtils.ps1
            # Remove non-release files 
            Remove-Item -Recurse -Force repo -Include .git*
            SignScubaGearModule `
              -AzureKeyVaultUrl https://githubautomationvault.vault.azure.net/ `
              -CertificateName ScubaCodeSigning-Dev `
              -ModulePath 'repo'
            Move-Item  -Path repo -Destination "ScubaGear-${env:RELEASE_VERSION}" -Force
            Compress-Archive -Path "ScubaGear-${env:RELEASE_VERSION}" -DestinationPath "ScubaGear-${env:RELEASE_VERSION}.zip"
          azPSVersion: "latest"
      - name: release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          name: ${{ inputs.releaseName }}
          tag_name: v${{ inputs.version }}
          files: ScubaGear-${{ inputs.version }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: true

