on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/run_publish_package.yaml"

name: Publish Package

env:
  GalleryName: PrivateScubaGearGallery
  ModuleName: ScubaGear
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  Publish-Private-Package:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
      - name: latest-tag 
        uses: actions-ecosystem/action-get-latest-tag@v1
        id: LatestTag 
        with:
          semver_only: true   
      - name: Load Deploy Utilities
        run: . src/utils/DeployUtils.ps1  
      - name: Register private PowerShell package repository
        run: New-PrivateGallery -GalleryName $env:GalleryName -Trusted
      - name: Publish ScubaGear Module 
        run: Publish-Module -Path src/PowerShell/ScubaGear -Repository $env:GalleryName
      - name: Test Module Publish
        run: |
          echo "${{ steps.latest-tag.outputs.tag}}"
          echo "${{ $env:GITHUB_CONTEXT }}"
  # Call-Smoke-Test:
  #   needs: Publish-Private-Package
  #   uses: ./.github/workflows/run_smoke_test.yaml

