on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/run_publish_package.yaml"
      - "utils/DeployUtils.ps1"

name: Publish Package

env:
  GalleryName: PrivateScubaGearGallery
  ModuleName: ScubaGear

jobs:
  Publish-Private-Package:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src  
      - name: Publish ScubaGear module to private repository
        run: |
          Get-PSRepository | fl
          cd src
          $sha = $(git rev-parse --short HEAD)
          $sha
          . utils/DeployUtils.ps1 
          $DebugPreference = "Continue" 
          New-PrivateGallery -GalleryName $env:GalleryName -Trusted
          New-CodeSigningCertificate
          Publish-ScubaGearModule -ModulePath PowerShell/ScubaGear -GalleryName $env:GalleryName -ModuleVersion '1.0.0'
      - name: Test Module Publish
        run: |
          Get-Location
          $TestContainers = @()
          $TestContainers += New-PesterContainer -Path "src/Testing/Functional/BuildTest" -Data @{ ModuleVersion = "1.0.0" }
          $PesterConfig = @{
            Run = @{
              Container = $TestContainers
            }
            Output = @{
              Verbosity = 'Detailed'
            }
          }
          $Config = New-PesterConfiguration -Hashtable $PesterConfig 
          Invoke-Pester -Configuration $Config 
      - name: Check Scuba Version 
        run: |
          Imstall-Module -Name ScubaGear
          Import-Module -Name ScubaGear
          Invoke-SCuBA -Version

