# Author: James Garriss
# Purpose: Run the product functional tests every night

name: Nightly Product Functional Tests

# Run this workflow at midnight 
# on every Mon to Fri (b/c GMT -5)
on:
  schedule:
  - cron: '0 4 * * 1-5'
  workflow_dispatch: 
  push:
    branches:
    - '652-add-nightly-product-functional-testing'

env:
  pfx-base64:    ${{ secrets.NIGHTLY_TEST_BUILD_PFX }}
  pfx-password:  ${{ secrets.NIGHTLY_TEST_BUILD_PW }} 
  pfx-base64-filename:  ./key-base64.txt
  pfx-filename:         ./key.pfx

jobs:
  sharepoint-test:
    name: SharePoint Test
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell 
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Create Base64 File
      run: "Out-File -FilePath $pfx-base64-filename -InputObject $pfx-base64 -Encoding ASCII"
    - run: dir
    - run: Get-Content $pfx-filename
    - name: Decode Base64 File
      run: |
        $data = Get-Content $pfx-base64-filename
        [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($data)) | Out-File -Encoding "ASCII" $pfx-filename
    # - name: Import Cert into Store
      # run: "Import-Certificate -FilePath .\key.cer -CertStoreLocation Cert:\CurrentUser\Root"
    - name: Import PFX into Store
      run: Import-PfxCertificate -Password (ConvertTo-SecureString -String $pfx-password -AsPlainText -Force) -CertStoreLocation Cert:\LocalMachine\Root -FilePath $pfx-filename
    - run: dir
    - run: Get-Content $pfx-filename
    # - name: Run Setup
    #   run: "./SetUp.ps1"
    # - name: Install Selenium
    #   run: "Install-Module -Name Selenium -RequiredVersion 3.0.1"
    # - name: Update Selenium
    #   run: "./Testing/Functional/SmokeTest/UpdateSelenium.ps1"
    # - name: Test SharePoint
    #   run: "./Testing/Functional/Products/Tests/CallProductTests.ps1"
