# Purpose: Run a secret scanner against the repo.

name: Run Secret Scan

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  secret-scan:
    name: MegaLint Gitleaks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Config File
        run: cp Testing/Linting/MegaLinter/.mega-linter-secret.yml .mega-linter.yml
      - name: Check Repo
        uses: oxsecurity/megalinter/flavors/security@latest
