# Purpose:  Run the CI/CD pipeline that tests, packages, and publishes ScubaGear.
# Note:  This pipeline is a work in progress.  At the moment, it is only doing linting, syntax checking, and unit testing.

name: Run the CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-yaml:
    name: Lint
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: ./.github/workflows/lint_yaml.yaml
  lint-powershell:
    name: Lint
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: ./.github/workflows/lint_powershell.yaml
  syntax:
    name: Syntax
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: ./.github/workflows/syntax_check_markdown.yaml
  unit-powershell:
    name: Unit
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: ./.github/workflows/unit_test_powershell.yaml
  unit-opa:
    name: Unit
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: ./.github/workflows/unit_test_opa.yaml
