# Purpose: Run one or more secret scanners against the entire repo.

name: Run Secret Scan

on:
  push:
    - 840-research-third-party-secret-scanners
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Scan with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
