# Purpose: Syntax checking for Markdown.

name: Markdown Check

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

jobs:
  Run-Markdown-Check:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    permissions:
      contents: read
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v4
      - name: Execute markdown checks
        run: |
          $PSVersionTable
          Invoke-Pester PowerShell\ScubaGear\Testing\Unit\PowerShell\CreateReport -Output Detailed
