# Purpose:  Run the CI/CD pipeline that tests, packages, and publishes ScubaGear.
# Note:  This pipeline is a work in progress.  At the moment, it is only doing linting, syntax checking, and unit testing.

name: Run the CI/CD Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  lint-yaml:
    name: Lint
    uses: ./.github/workflows/lint_yaml.yaml
  lint-powershell:
    name: Lint
    uses: ./.github/workflows/lint_powershell.yaml
  scan-secret:
    name: Security
    uses: ./.github/workflows/run_secret_scan.yaml
  check-security:
    name: Security
    uses: ./.github/workflows/check_security.yaml
  syntax-markdown:
    name: Syntax
    uses: ./.github/workflows/syntax_check_markdown.yaml
  unit-powershell:
    name: Unit
    uses: ./.github/workflows/unit_test_powershell.yaml
  unit-opa:
    name: Unit
    uses: ./.github/workflows/unit_test_opa.yaml
