# Purpose:  Run the CI/CD pipeline that tests, packages, and publishes ScubaGear.
# Note:  This pipeline is a work in progress.  At the moment, it is only doing linting, syntax checking, and unit testing.

name: CI/CD Pipeline

on:
  push:
    branches:
      - 825-create-initial-software-dev-pipeline
  pull_request:
  workflow_dispatch:

jobs:
  lint-yaml:
    name: Lint
    uses: cisagov/ScubaGear/.github/workflows/run_linter_yaml.yaml@825-create-initial-software-dev-pipeline
  lint-powershell:
    name: Lint
    uses: cisagov/ScubaGear/.github/workflows/run_linter_powershell.yaml@825-create-initial-software-dev-pipeline
  syntax:
    name: Syntax
    uses: cisagov/ScubaGear/.github/workflows/run_markdown_check.yaml@825-create-initial-software-dev-pipeline
    needs: [lint-yaml, lint-powershell]
  # unit:
  #   needs: [lint, syntax]
