on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Release Name"
        required: true
        type: string
      version:
        description: "Release Version (e.g., 1.2.4)"
        required: true
        type: string
      useDevCredentials:
        description: "Use development instead of production credentials"
        required: false
        type: boolean
        default: true

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      SCUBA_CODE_SIGNING_CREDS: ${{ secrets.SCUBA_CODE_SIGNING_CREDS }}
      CODESIGN_PW: ${{ secrets.CODESIGN_PW }}
      CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
      RELEASE_VERSION: ${{ inputs.version }}
    permissions:
      contents: write
    steps:
      - name: Install AzureSignTool
        shell: pwsh
        run: |
          dotnet --version
          dotnet tool install --global AzureSignTool --version 4.0.1
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Sign Module
        shell: pwsh
        run: |
          $env:SCUBA_CODE_SIGNING_CREDS
          $CREDS = $env:SCUBA_CODE_SIGNING_CREDS 
          $CREDS
          if (${{ inputs.useDevCredentials }} -eq 'true'){
            $CREDS = $CREDS.Development
          }
          else {
            $CREDS = $CREDS.Production
          }
          . repo/utils/DeployUtils.ps1
          SignScubaGearModule `
            -AzureKeyVaultUrl $($CREDS.KeyVault.URL) `
            -CertificateName $($CREDS.KeyVault.Certificate) `
            -ClientId $($CREDS.ServicePrincipal.ClientId) `
            -ClientSecret $($CREDS.ServicePrincipal.Secret) `
            -TenantId $($CREDS.ServicePrincipal.TenantId) `
            -ModulePath 'repo'
      - name: release
        shell: bash
        run: |
          echo "TODO"

