name: Run PS Linter

on:
  push:
    branches:
      - "759-consolidate-redundant-ps-linting"
    # paths:
    #   - '**.ps1'
    #   - '**.psm1'
    #   - '**.psd1'
    #   - '**.pssc'
    #   - '**.psrc'
    #   - '**.ps1xml'
    #   - '**.cdxml'
  # pull_request:
  #   types: [opened, reopened]
  #   branches:
  #     - "main"
  #   paths:
  #     - "**.ps1"
  #     - "**.psm1"
  # workflow_dispatch:

jobs:
  lint:
    name: PS Script Analyzer Check
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   issues: write
    #   pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint PowerShell
        uses: devblackops/github-action-psscriptanalyzer@master
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          # settingsPath: PSScriptAnalyzerSettings.psd1
          # failOnErrors: true
          # failOnWarnings: true
          # failOnInfos: true
          # sendComment: true
