# Author: James Garriss
# Purpose: Run the product functional tests every night

name: Nightly Product Functional Tests

# Run this workflow at midnight 
# on every Mon to Fri (b/c GMT -5)
on:
  schedule:
  - cron: '0 4 * * 1-5'
  workflow_dispatch: 
  push:
    branches:
    - '652-add-nightly-product-functional-testing'

jobs:
  sharepoint-test:
    name: SharePoint Test
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell 
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Check for SharePoint test
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "./Testing/Functional/Products/Tests/sharepoint-commercial.ps1"
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      # Only runs if all of the files exists
      run: echo SharePoint file exists!
    # - name: Test SharePoint
    #   run: |
    #     .\Testing\Functional\Products\Tests\sharepoint-commercial.ps1 FD6219CFBF937830616E43DF9C81BCF7D22FE03F
