on: 
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/run_publish_package.yaml"

name: Publish Package

env:
  GalleryName: PrivateScubaGearGallery
  ModuleName: ScubaGear

jobs:
  Publish-Private-Package:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src  
      - name: Load Deploy Utilities
        run: . src/utils/DeployUtils.ps1  
      - name: Register private PowerShell package repository
        run: New-PrivateGallery -GalleryName $env:GalleryName -Trusted
      - name: Publish ScubaGear Module 
        run: Publish-ScubaGearModule -Path src/PowerShell/ScubaGear -Repository $env:GalleryName -ModuleVersion '1.0.0'
      - name: Test Module Publish
        run: |
          $sha = $(git rev-parse --short HEAD)
          echo "${{ steps.latest-tag.outputs.tag}}"
          echo "$Sha"
  # Call-Smoke-Test:
  #   needs: Publish-Private-Package
  #   uses: ./.github/workflows/run_smoke_test.yaml

