# Purpose: Run unit tests for PowerShell

name: Run PowerShell Tests

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

jobs:
  Run-PowerShell-Tests:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Pester Tests
        if: "!cancelled()"
        shell: powershell
        run: |
          Invoke-Pester -Output 'Detailed' -Path 'PowerShell/ScubaGear/Testing/Unit/PowerShell'
