# Author: James Garriss
# Purpose: Run the linter against the PowerShell code (and others)

name: Lint Check

# Run whenever code is checked in
on:
  push:
    branches:
    - '700-add-powershell-linter'

jobs:
  lint-check:
    name: Mega-Lint Check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Docker Pull
      run: docker pull oxsecurity/megalinter
    - name: Docker Run
      run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock:rw -v $(pwd):/tmp/lint:rw oxsecurity/megalinter:v7
      