# Purpose: Run unit tests for OPA

name: Run OPA Tests

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

env:
  MODULE_ROOT: PowerShell/ScubaGear
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: Run OPA Check
        run: opa check ${{ env.MODULE_ROOT }}/Rego ${{ env.MODULE_ROOT }}/Testing/Unit/Rego --strict
      - name: Run OPA Tests
        run: opa test ${{ env.MODULE_ROOT }}/Rego/*.rego ${{ env.MODULE_ROOT }}/Rego/Utils/*.rego ${{ env.MODULE_ROOT }}/Testing/Unit/Rego/**/*.rego -v
      - name: Setup Regal
        uses: StyraInc/setup-regal@v0.2.0
        with:
          version: v0.11.0
      - name: Run Regal Lint
        run: regal lint --format github ${{ env.MODULE_ROOT }}/Rego ${{ env.MODULE_ROOT }}/Testing
