on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: "Release Name"
        required: true
        type: string
      version:
        description: "Release Version (e.g., 1.2.4)"
        required: true
        type: string
      useDevCredentials:
        description: "Use development instead of production credentials"
        required: false
        type: boolean
        default: true

name: Build and Sign Release

jobs:
  build-and-deploy:
    runs-on: windows-latest
    #environment: CodeSigning
    env:
      SCUBA_CODE_SIGNING_CREDS: ${{ secrets.SCUBA_CODE_SIGNING_CREDS }}
      CODESIGN_PW: ${{ secrets.CODESIGN_PW }}
      CODESIGN_PFX: ${{ secrets.CODESIGN_PFX }}
      RELEASE_VERSION: ${{ inputs.version }}
      AZURE_CLIENT_ID: 013a0852-8e4d-419e-8571-e9305844095d
      AZURE_TENANT_ID: 3c19c757-3b55-411f-b03f-2bcc514a598d
      AZURE_SUBSCRIPTION_ID: 1c838bbe-dea0-42ce-a0a8-13e997b65bde
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: $env:AZURE_CLIENT_ID
          tenant-id: $env:secrets.AZURE_TENANT_ID
          subscription-id: $env:secrets.AZURE_SUBSCRIPTION_ID
          enable-AzPSSession: true          
      - name: Sign Module
        uses: azure/powershell@v1
        with:
          inlineScript: |
            dotnet --version
            dotnet tool install --global AzureSignTool --version 4.0.1
            $CREDS = $env:SCUBA_CODE_SIGNING_CREDS | ConvertFrom-Json
            if (${{ inputs.useDevCredentials }} -eq 'true'){
              $CREDS = $CREDS.Development
            }
            else {
              $CREDS = $CREDS.Production
            }
            . repo/utils/DeployUtils.ps1
            SignScubaGearModule `
              -AzureKeyVaultUrl $($CREDS.KeyVault.URL) `
              -CertificateName $($CREDS.KeyVault.Certificate) `
              -ModulePath 'repo'
          azPSVersion: "latest"
      - name: release
        shell: pwsh
        run: |
          Get-Content -Path repo\PowerShell\ScubaGear\RequiredVersions.ps1

