name: Nightly Product Functional Tests

# Run this workflow at midnight 
# on every Mon to Fri (b/c GMT -5)
on:
  schedule:
  - cron: 0 4 * * 1-5
  workflow_dispatch: 

jobs:
  hello-world-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
      # Let's start simple: Just cat the file
    - name: View test file
      run: cat Testing/Functional/Products/Products.Tests.ps1
