# Purpose: Run a secret scanner against the repo.

name: Scan for Secrets

on:
  workflow_call:
  workflow_dispatch:

jobs:
  secret-scan:
    name: MegaLint Gitleaks
    runs-on: ubuntu-latest
    # This condition prevents duplicate runs.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Config File
        run: cp Testing/Linting/MegaLinter/.mega-linter-secret.yml .mega-linter.yml
      - name: Check Repo
        uses: oxsecurity/megalinter/flavors/security@latest
