name: Test Write

on:
  workflow_dispatch:
  push:

permissions: read-all

jobs:
  test:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
    defaults:
      run:
        shell: powershell
    steps:
      - name: Write Me
        run: |
          Write-Debug "Debug"
          Write-Host "Host"
          Write-Information "Information"
          Write-Output "Output"
          Write-Progress "Progess"
          Write-Verbose "Verbose"
          Write-Warning "Warning"
          Write-Error "Error"
          Write-Host "Does this print after error?"