# Purpose: Run unit tests for the code used in workflows

name: Unit Test Workflow

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

permissions: read-all

jobs:
  workflow-tests:
    name: Workflow Unit Tests
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run Pester Tests
        run: |
          # This should run all workflow unit tests
          Try {
            Invoke-Pester -CI -Output 'Detailed' -Path 'Testing/workflow/fakedirectory' -ErrorVariable err
            $err.Count | Should -Not -Be 0
          } Catch {
            Throw "Something went wrong!"
          }
