# Purpose: Run unit tests for OPA

name: Unit Test OPA

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
  workflow_dispatch:

env:
  MODULE_ROOT: PowerShell/ScubaGear
jobs:
  opa-tests:
    name: OPA Unit Tests
    runs-on: ubuntu-latest
    # This condition prevents duplicate runs.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest
      - name: Run OPA Check
        run: opa check ${{ env.MODULE_ROOT }}/Rego ${{ env.MODULE_ROOT }}/Testing/Unit/Rego --strict
      - name: Run OPA Tests
        run: opa test ${{ env.MODULE_ROOT }}/Rego/*.rego ${{ env.MODULE_ROOT }}/Rego/Utils/*.rego ${{ env.MODULE_ROOT }}/Testing/Unit/Rego/**/*.rego -v
      - name: Setup Regal
        uses: StyraInc/setup-regal@v1.0.0
        with:
          version: v0.18.0
      - name: Run Regal Lint
        run: regal lint --format github ${{ env.MODULE_ROOT }}/Rego ${{ env.MODULE_ROOT }}/Testing
